this

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -62,7 +62,7 @@ jobs:
       env:
           GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
     - name: Docker push
-      run: docker push ghcr.io/berlingoqc/openbruno/cli:$(npm run version --silent) || echo "failed to publish, version not updated"
+      run: cd packages/bruno-cli && docker push ghcr.io/berlingoqc/openbruno/cli:$(npm run version --silent) || echo "failed to publish, version not updated"
 
   release:
     runs-on: ubuntu-latest
